<!-- This page was generated by Gemini -->
<!-- Backend needed on Ln91 -->



<template>
  <div class="auth-page">
    <div class="auth-card">
      
      <div class="toggle-container">
        <div 
          class="toggle-slider" 
          :style="{ transform: activeTab === 'login' ? 'translateX(0)' : 'translateX(100%)' }"
        ></div>
        <button 
          class="toggle-btn" 
          :class="{ active: activeTab === 'login' }"
          @click="handleTabChange('login')"
        >
          Login
        </button>
        <button 
          class="toggle-btn" 
          :class="{ active: activeTab === 'register' }"
          @click="handleTabChange('register')"
        >
          Register
        </button>
      </div>

      <h2 class="title">{{ activeTab === 'login' ? 'Welcome Back!' : 'Create Account' }}</h2>

      <form @submit.prevent="handleSubmit" class="auth-form">
        
        <div class="input-group" v-if="activeTab === 'register'">
          <label>Full Name</label>
          <input v-model="formData.name" type="text" placeholder="John Doe" required />
        </div>

        <div class="input-group">
          <label>Email Address</label>
          <input v-model="formData.email" type="email" placeholder="example@email.com" required />
        </div>

        <div class="input-group">
          <label>Password</label>
          <input v-model="formData.password" type="password" placeholder="••••••••" required />
        </div>

        <button type="submit" class="submit-btn" :disabled="isLoading">
          {{ isLoading ? 'Processing...' : (activeTab === 'login' ? 'Sign In' : 'Sign Up') }}
        </button>
      </form>

      <p class="status-msg" v-if="status">{{ status }}</p>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'

const activeTab = ref('login')
const isLoading = ref(false)
const status = ref('')

// Form data structure
const formData = reactive({
  name: '',
  email: '',
  password: ''
})

// Function to clear all fields
const clearForm = () => {
  formData.name = ''
  formData.email = ''
  formData.password = ''
  status.value = ''
}

// Handle tab switching with clearing
const handleTabChange = (tab) => {
  if (activeTab.value !== tab) {
    activeTab.value = tab
    clearForm() // This ensures fields are empty on switch
  }
}

const handleSubmit = async () => {
  isLoading.value = true                  //A Gemini szerint ide jön a backend
  status.value = ''

  // Simulation
  setTimeout(() => {
    isLoading.value = false
    
    if (activeTab.value === 'login') {
      status.value = `Successfully logged in: ${formData.email}`
    } else {
      status.value = `Account created for: ${formData.name}`
    }
    
    console.log("Sent data:", JSON.parse(JSON.stringify(formData)))
  }, 1500)
}
</script>

<style scoped>
.auth-page {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
  font-family: 'Inter', sans-serif;
}

.auth-card {
  background: white;
  padding: 40px;
  border-radius: 24px;
  box-shadow: 0 15px 35px rgba(0,0,0,0.1);
  width: 100%;
  max-width: 400px;
  text-align: center;
}

.toggle-container {
  display: flex;
  background: #eee;
  padding: 4px;
  border-radius: 12px;
  position: relative;
  margin-bottom: 30px;
}

.toggle-slider {
  position: absolute;
  top: 4px;
  left: 4px;
  width: calc(50% - 4px);
  height: calc(100% - 8px);
  background: #007aff;
  border-radius: 8px;
  transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  z-index: 1;
}

.toggle-btn {
  flex: 1;
  padding: 10px;
  border: none;
  background: none;
  font-weight: 600;
  cursor: pointer;
  position: relative;
  z-index: 2;
  transition: color 0.3s;
  color: #666;
}

.toggle-btn.active {
  color: white;
}

.title {
  margin-bottom: 25px;
  color: #2c3e50;
}

.auth-form {
  text-align: left;
}

.input-group {
  margin-bottom: 20px;
}

.input-group label {
  display: block;
  font-size: 0.85rem;
  color: #7f8c8d;
  margin-bottom: 5px;
  font-weight: 600;
}

.input-group input {
  width: 100%;
  padding: 12px;
  border: 2px solid #edf2f7;
  border-radius: 10px;
  outline: none;
  transition: border-color 0.2s;
}

.input-group input:focus {
  border-color: #007aff;
}

.submit-btn {
  width: 100%;
  padding: 14px;
  background: #007aff;
  color: white;
  border: none;
  border-radius: 10px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  margin-top: 10px;
  transition: transform 0.1s, background 0.2s;
}

.submit-btn:active {
  transform: scale(0.98);
}

.submit-btn:disabled {
  background: #a0aec0;
  cursor: not-allowed;
}

.status-msg {
  margin-top: 20px;
  font-size: 0.9rem;
  color: #2ecc71;
}
</style>