<!-- This was generated by Gemini -->
<!-- EXAMPLE LINK IN LN76  -->


<template>
  <div class="qr-app">
    <div class="content-area">
      
      <div v-if="activeTab === 'generator'" class="tab-content generator-fade">
        <div class="card">
          <h1>QR-kód</h1>
          
          <div class="qr-wrapper">
            <img 
              :src="`https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=${encodeURIComponent(fixLink)}`" 
              alt="QR Kód"
              class="qr-image"
            />
          </div>

        </div>
      </div>

      <div v-if="activeTab === 'camera'" class="tab-content camera-fade">
        <div class="card camera-card">
          <h1>QR-kód Beolvasása</h1>
          <p class="subtitle">Irányítsd a kamerát a kódra!</p>
          
          <div id="reader" class="camera-reader"></div>
          
          <div v-if="scannedResult" class="scan-result success">
            <strong>Sikeres beolvasás!</strong>
            <p>{{ scannedResult }}</p>
            <button @click="startScanning" class="action-btn">Újra</button>
          </div>
          
          <div v-else-if="scanError" class="scan-result error">
            {{ scanError }}
          </div>
        </div>
      </div>
    </div>

    <div class="bottom-nav">
      <div 
        class="nav-slider" 
        :style="{ '--active-index': activeTabIndex }"
      ></div>
      
      <button 
        class="nav-btn" 
        :class="{ active: activeTab === 'camera' }" 
        @click="switchTab('camera')"
      >
        <Icon name="uil:camera" class="nav-icon" />
        Camera
      </button>
      
      <button 
        class="nav-btn" 
        :class="{ active: activeTab === 'generator' }" 
        @click="switchTab('generator')"
      >
        <Icon name="uil:qrcode-scan" class="nav-icon" />
        QR-code
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'

// ALAP ADATOK
const fixLink = ref('https://en.wikipedia.org/wiki/Hide_the_Pain_Harold')        //Example link, change it to dinamic
const activeTab = ref('generator')
const scannedResult = ref(null)
const scanError = ref(null)
let html5QrCode = null

// SZÁMÍTOTT ÉRTÉKEK a csúszkához
const tabs = ['camera', 'generator']
const activeTabIndex = computed(() => tabs.indexOf(activeTab.value))

// FÜGGVÉNYEK

// 1. Váltás a két mód között
const switchTab = (tabName) => {
  activeTab.value = tabName
  
  if (tabName === 'camera') {
    scannedResult.value = null
    scanError.value = null
    startScanning()
  } else {
    stopScanning()
  }
}


const startScanning = () => {
  if (!process.client || !window.Html5Qrcode) return;

  scanError.value = null;
  scannedResult.value = null;


  stopScanning();

  // Létrehozzuk az új scannert
  html5QrCode = new Html5Qrcode("reader");

  const config = { fps: 10, qrbox: { width: 250, height: 250 } };

  // Indítás
  html5QrCode.start(
    { facingMode: "environment" }, // Hátsó kamera
    config,
    (decodedText) => {
      // SIKER!
      scannedResult.value = decodedText;
      stopScanning(); // Leállítjuk a sikeres scan után
      console.log("Beolvasva:", decodedText);
    },
    (errorMessage) => {
      // Hiba (pl. nem lát kódot), ezt nem írjuk ki pirossal, csak logoljuk
      // console.log("Hiba:", errorMessage);
    }
  ).catch((err) => {
    // Kritikus hiba (pl. nincs kamera engedély)
    scanError.value = `Kamera indítási hiba: ${err}`;
    console.error(err);
  });
}

// 3. Kamera Leállítása
const stopScanning = () => {
  if (html5QrCode && html5QrCode.isScanning) {
    html5QrCode.stop().then(() => {
      console.log("Kamera leállítva.");
    }).catch((err) => {
      console.error("Hiba a leállításkor:", err);
    });
  }
}

// ÉLETCYKLUS (Kamera script betöltése)
onMounted(() => {
  // Ha már be van töltve (pl. frissítésnél), azonnal rajzolunk
  if (window.Html5Qrcode) return;

  // Ha nincs, betöltjük dinamikusan
  const script = document.createElement('script')
  script.src = 'https://unpkg.com/html5-qrcode@2.3.8/html5-qrcode.min.js'
  script.async = true
  script.onload = () => {
    console.log("Kamera script betöltve.");
  }
  document.head.appendChild(script)
})

onBeforeUnmount(() => {
  stopScanning() // Biztonsági leállítás kilépéskor
})
</script>

<style scoped>
/* ALAP STÍLUSOK */
.qr-app {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  font-family: 'Segoe UI', sans-serif;
  background-color: #f0f3f6;
  padding-bottom: 90px;
}

/* TARTALOM TERÜLET */
.content-area {
  flex: 1;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 20px;
}

.tab-content {
  width: 100%;
  max-width: 400px;
}

/* ÁTTŰNÉSI ANIMÁCIÓK */
.generator-fade { animation: fadeIn 0.5s ease; }
.camera-fade { animation: slideInUp 0.5s ease; }

@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
@keyframes slideInUp { from { transform: translateY(20px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }

/* KÁRTYA DESIGN */
.card {
  background: white;
  padding: 30px;
  border-radius: 20px;
  box-shadow: 0 10px 30px rgba(0,0,0,0.05);
  text-align: center;
}

h1 { color: #2c3e50; font-size: 1.6rem; margin-bottom: 5px; }
.subtitle { color: #7f8c8d; font-size: 0.9rem; margin-bottom: 30px; }

/* GENERÁTOR MÓD */
.qr-wrapper {
  background: #fdfdfd;
  padding: 15px;
  border: 1px solid #eee;
  border-radius: 12px;
  display: inline-block;
}
.qr-image { display: block; width: 200px; height: 200px; }
.link-display { margin-top: 20px; padding: 10px; background: #ecf0f1; border-radius: 8px; }
.link-display code { color: #e67e22; font-weight: bold; word-break: break-all; font-size: 0.8rem; }

/* BEOLVASÓ MÓD */
.camera-card { padding: 20px; }
.camera-reader {
  width: 100%;
  max-width: 300px;
  height: 300px;
  margin: 0 auto;
  background: #000;
  border-radius: 12px;
  overflow: hidden; /* Lekerekíti a videót is */
  border: 4px solid #fff;
}

.scan-result { margin-top: 20px; padding: 15px; border-radius: 8px; }
.scan-result.success { background-color: #e8f8f1; color: #00dc82; border: 1px solid #c3f3e1; }
.scan-result.error { background-color: #fceeea; color: #ff4d4d; border: 1px solid #facfce; }
.action-btn { margin-top: 10px; cursor: pointer; padding: 8px 15px; border-radius: 4px; border: none; background: #00dc82; color: white; }

/* ALSÓ NAVIGÁCIÓ (A NAGY KÉK HASÁB) */
.bottom-nav {
  position: fixed;
  bottom: 20px;
  left: 50%;
  transform: translateX(-50%);
  width: 90%;
  max-width: 400px;
  height: 65px;
  background-color: #004a99; /* Nagy sötétkék hasáb */
  border-radius: 40px;
  display: flex;
  justify-content: space-around;
  align-items: center;
  padding: 0 5px;
  box-shadow: 0 10px 30px rgba(0, 74, 153, 0.3);
  z-index: 100;
  overflow: hidden; /* Hogy a csúszka ne lógjon ki */
}

/* A CSÚSZKA LEKEREKÍTETT HASÁB */
.nav-slider {
  position: absolute;
  top: 5px;
  left: 5px;
  height: calc(100% - 10px);
  width: calc(50% - 5px); /* A hasáb fele */
  background-color: #0eed2c; /* Lekerekített kék hasáb */
  border-radius: 35px;
  
  /* Ez a varázslat: a '--active-index' alapján csúszik át */
  transform: translateX(calc(100% * var(--active-index)));
  
  /* Smooth animáció */
  transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  z-index: -1;
}

/* A GOMBOK */
.nav-btn {
  background: none;
  border: none;
  flex: 1;
  height: 100%;
  color: #fff;
  opacity: 0.6;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 5px;
  transition: opacity 0.3s, color 0.3s;
}

/* Az aktív gomb stílusa */
.nav-btn.active {
  opacity: 1;
  color: #fff;
}

.nav-icon { font-size: 1.4rem; }
</style>